export const USER_LOGIN = 'USER_LOGIN'
export const USER_SEND_LOGIN = 'USER_SEND_LOGIN'
export const USER_RESET_SEND_LOGIN = 'USER_RESET_SEND_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_INFO = 'USER_INFO'
export const USER_UPDATE_STATUS = 'USER_UPDATE_STATUS'

export const MEMBERS_GET = 'MEMBERS_GET'
export const MEMBERS_UPDATE_STATUS = 'MEMBERS_UPDATE_STATUS'

export const CONVERSATION_GET = 'CONVERSATION_GET'
export const CONVERSATION_SET_LOADING = 'CONVERSATION_SET_LOADING'
